# Generated by Django 3.1 on 2020-08-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='Merchandise',
            new_name='merchandise',
        ),
    ]
