# Generated by Django 3.1 on 2020-08-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='league',
            new_name='division',
        ),
    ]
