# Generated by Django 3.1 on 2020-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20200809_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='year',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='game_used',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='signed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
