# Generated by Django 3.1 on 2020-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_auto_20200811_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='font_awesome',
            field=models.CharField(default='fas fa-football-ball', max_length=254),
        ),
    ]
